### ISSUE TITLE
Support gym and gymnasium converter.

### ISSUE THREAD

**Issue by ethanluoyc** [kevinzakka/dm_env_wrappers#1]
Hey!

I was wondering if you would be willing to put a gym and gymnasium wrapper in this repo. These are wrappers that I use quite regularly from Acme and it would be quite helpful for them to be put here so that we can use them outside the Acme package.

More concretely, to avoid having these as a required dependency, I think we can [`lazy-import`](https://github.com/google-deepmind/launchpad/blob/master/launchpad/lazy_loader.py) these. This is what I do from one of my project in progress.

```python
from corax.utils import lazy_loader

with lazy_loader.LazyImports(__name__, False):
    # This would expose these symbols as top-level classes while still not depending on gym and gymnasium.
    from corax.wrappers.gym_wrapper import GymWrapper
    from corax.wrappers.gymnasium_wrapper import GymnasiumWrapper
del lazy_loader

```

**Comment by kevinzakka** [comment]
Hi @ethanluoyc, yeah I think it makes a lot of sense to have them in here. Would you be willing to make a PR?

**Comment by ethanluoyc** [comment]
Created #2
